language: java
install: true

addons:
  sonarcloud:
    organization: "p3pp3rf1y-github"
    token: SONAR_TOKEN

jdk:
- oraclejdk8

script:
- "./gradlew clean"
- "./gradlew setupCIWorkspace"
- "./gradlew build"
- "./gradlew bintrayUpload"

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'